#!/bin/bash

set -xe

export NODEBREW_ROOT=$OPENSHIFT_DATA_DIR/.nodebrew
export PATH=$NODEBREW_ROOT/current/bin:$PATH

npm install --production
npm install -g forever@0.15.1

forever list
forever start --uid irori -fa bin/www
forever list
